Miao/homepage/latest workshop slider/006
SheCodesAus/she-codes-group-project-frontend-fullstack-pancake pull request #7
Opened 2022-09-01 12:09 UTC by miaozhaod

2022-09-01 22:57 UTC, builtbyproxy requested changes
As discussed on slack, I'll review and nitpick, ignore at your discretion, I'm out of the loop on scope and timelines so don't let me delay you.

2022-09-01 22:57 UTC, builtbyproxy commented on src/components/Slider/LatestWorkshopSlideCard.jsx
> +export default function LatestWorkshopSlideCard({ slides, current }) {
Since you're only using current to access an index of the slides array, I'd like to see current be currentIndex or something that communicates how it's used. 

Current implies there is a past, which at a glance on first pass makes me thing there's more happening here.

2022-09-01 22:57 UTC, builtbyproxy commented on src/components/Slider/index.jsx
> +        <LatestWorkshopSlideCard slides={slides} current={current} />
If this only uses one slide, you should store that slide in state OR just pass that slide like so: 
```suggestion
        <LatestWorkshopSlideCard slide={slides[current]} />
```

The way you currently access it, is forcing the `<LatestWorkshopSlideCard/>` component to find it in an array every time it wants to use a field such as title, image or location. By accessing the array once and then providing the specific object it can be a lot more performant 😊

2022-09-01 22:57 UTC, builtbyproxy commented on src/components/Slider/index.jsx
> +          &#8811;
Add a comment above this for what it will display. I'm just looking at a gibberish unicode for now haha

2022-09-02 07:15 UTC, miaozhaod commented on src/components/Slider/LatestWorkshopSlideCard.jsx
> +export default function LatestWorkshopSlideCard({ slides, current }) {
Agree, when I look it back, I also need to think of what I was trying to communicate here, I updated this to `currentSlideIndex`, would be easy for understanding

2022-09-02 07:20 UTC, miaozhaod commented on src/components/Slider/index.jsx
> +        <LatestWorkshopSlideCard slides={slides} current={current} />
This is exactly where I was feeling weird when passing the currentIndex as a props to the WorkshopSlideCard, I updated as the way you suggested here with the renamed `currentSlideIndex`

2022-09-02 07:25 UTC, miaozhaod commented on src/components/Slider/index.jsx
> +          &#8811;
yah, I've added a comment here, these are two symbols of arrows for `go to previous/next slide`

2022-09-02 09:55 UTC, builtbyproxy approved these changes
Nice work! 

One final point, when you make a commit to address a comment someone has made (me in this case), can yu please also include the commit hash to show where you fixed it. 

For example: 
> I've addressed that here: a6788fb9bd23db1df521709a7cbe64e1de50ec1e

2022-09-02 09:55 UTC, builtbyproxy commented on src/components/Slider/index.jsx
> +          &#8811;
Nice work

2022-09-02 11:42 UTC, miaozhaod commented
> 

Gotcha, thanks! will do this moving forward

2022-09-02 11:42 UTC, merged